core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import django.core.handlers.wsgi
from . import views 
from django.conf.urls.static import static
from django.conf import settings
from .forms import LoginForm, SignUpForm, AuthenticationForm, EmailAuthenticationForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', django.contrib.auth.views.LoginView.as_view(template_name= 'mvp-2.html', authentication_form= LoginForm), name='mvp'),
    url(r'^ordermanage/', include("ordermanage.urls")),
    url(r'^signup/$', views.signup, name='signup'),      
    url(r'^logout/$',auth_views.LogoutView.as_view(), name='logout'),
    url(r'^shop/', include('shop.urls',  namespace='shop')),
    url(r'^wallmart/', include("wallmart.urls")),
    url(r'^ups/', include('ups.urls')),
    url(r'^shopify_app/', include('shopify_app.urls')),
    url(r'^ebay/', include("ebayshop.urls")),
    url(r'^amazon/', include("amazon.urls")),
    url(r'^fedex/', include("fedex.urls")),
    
    # PASSWWORD VIEWS - AUTH BASED.

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('rest_framework_social_oauth2.urls')), #heroku comment
]


"""for Lodaing Static files in django """

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""End Of  Lodaing Static files in django """

shop/urls.py
from django.conf.urls import url
from . import views
app_name='shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<id>\d+)/delete/$', views.product_delete, name="delete"),
    #url(r'^/create/$', views.create, name="create"),
    url(r'^product/create/$', views.create, name="create"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/company_stock/$', views.company_stock, name='company_stock'),
    url(r'^product/category/$', views.category, name='category'),
    url(r'^product/addcompany/$', views.AddCompanySku, name='addcompany'),
    url(r'^product/company/$', views.AddCompany, name='company'),
    url(r'^product/hundred/$', views.inventory_hundred_Percent, name='hundred'),
    url(r'^product/lesthantwenty/$', views.inventory_twenty, name='lesthantwenty'),
    url(r'^product/inventory_inrange/$', views.inventory_inrange, name='inventory_inrange'),
    url(r'^product/create_product/$', views.CreateProduct, name='create_product'),
    url(r'^product/shopifyGetProduct/$', views.shopifyGetProduct, name='shopifyGetProduct')
    # url(r'^company_stock/$', views.company_stock, name='company_stock'),



]

ups/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # url(r'^$', views.index, name="index")
    url(r'^$', views.UpsCreateShipment, name="ship"),
    url(r'^recovery/$', views.LabelRecoveryRequest, name="recovery"),
    url(r'^void/$', views.UpsVoidShipment, name="void"),
    url(r'^track/$', views.GetTrackingNumber, name="track"),
    url(r'^track_signature/$', views.GetTrackingNumber, name="track_signature"),
    url(r'^image_converter/$', views.image_converter, name="image_converter"),
    url(r'^address_validater/$', views.UpsAddressValidation, name="address_validater"),
    url(r'^add_upsaccount/$', views.AddUpsAccount, name="add_upsaccount"),
    url(r'^add_shipper/$', views.AddUpsShipper, name="add_shipper"),
    url(r'^add_shipfrom/$', views.AddShipFrom, name="add_shipfrom"),
    url(r'^sipper_list/$', views.ShipperListDisplay, name="sipper_list"),
    url(r'^shipfrom_list/$', views.ShipfromListDisplay, name="shipfrom_list"),
    url(r'^csv/$', views.ReadFromCsv, name="csv"),
    url(r'^exls/$', views.ReadFromExls, name="exls"),
    url(r'^shipment/$', views.CreateShipment, name="shipment")

]
 

shop/models.py
from django.db import models
from django.urls import reverse
from django.core.signals import request_finished
from django.db.models.signals import pre_save
from django.dispatch import receiver
# from ordermanage.models import Company1


#
class Category(models.Model): 
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
 
class Product(models.Model):#inventry table  
    
    # Product_id = models.PositiveIntegerField(default=None, blank=True, null=True ) #remove True
    Product_SKU = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=200, db_index=True) # name of the product
    slug = models.SlugField(max_length=200, db_index=True,) # built beautiful url 
    image = models.FileField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    bulletpoints = models.TextField(blank=True)
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    Product_Dimensions = models.CharField(max_length=20, blank = False ,null = False)
    Color = models.CharField(blank = False ,null = False, max_length=20)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    block_quantity = models.IntegerField(default=0, blank=True, null=True)
    available_quentity= models.IntegerField(default=1, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)    
    updated = models.DateTimeField(auto_now=True)    
    Material_Type = models.CharField(blank = False ,null = False, max_length=40) #
    Model_Number = models.CharField(blank = True ,null = True, max_length=40) #optional
    ASIN = models.CharField(blank = True ,null = True, max_length=20) #optional

    class Meta: 
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
    
    def __str__(self, **kwargs):
        return self.name
    
    def __str__(self):
        return self.Product_SKU

    # def get_absolute_url(self):
    #     return reverse('shop:product_detail', args=[self.id, self.slug])

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class CompanyName(models.Model):
    companyname_id = models.AutoField(primary_key=True)
    companyname = models.CharField(max_length=250, unique=True )
    
    

    def __str__(self):
        return self.companyname


class Company(models.Model): 
    Product_SKU = models.ForeignKey(Product, related_name='prd_sku',on_delete=models.CASCADE)
    company_sku =  models.CharField(max_length=255, unique=True)
    company_name=models.ForeignKey(CompanyName, related_name='company_name',on_delete=models.CASCADE)
    # height = models.IntegerField(max_length=20)
    # width = models.IntegerField(max_length=20)
    # Company_Unit_Price= models.CharField(max_length=255)
    # Company_Retail_Price = models.CharField(max_length=255)
    # UPC/GTIN = models.IntegerField(max_length=20
    
    
    def __str__(self):
        return str(self.company_name)

    # def __str__(self):
    #    return self.company_name

class Manufacturer(models.Model):

    manufacturer_sku=models.CharField(max_length=250)
    manufacturer_name=models.CharField(max_length=250)
    manufacturer_product_Quantity =models.IntegerField(default=0)
    # Product_SKU = models.ForeignKey(Product, related_name='Manu_prd_sku')

    # def __str__(self):
    #     return (self.manufacturer_sku)

    


# def check_inventery(sender, **kwargs):#RECIVER
#     # if kwargs['created']:
#         #create_inventory= Order.objects.create(user=kwargs['instance'])
#     #create_inventory= Order.objects.create(user=kwargs['instance'])
#     quantity= Product.objects.all()
#     print quantity
#     print "message is recived"

class ShopifyProductDetails(models.Model):
    product_sku = models.CharField(max_length=256)
    product_id= models.CharField(max_length=256, unique=True)
    variants_id= models.CharField(max_length=256)
    options_id = models.CharField(max_length=256)
    images_id = models.CharField(max_length=256)

    def __unicode__(self):
        return self.product_id



    

shop/forms.py
from django import forms
from django.forms import MultiWidget
from .models import *

#FOR DISPLAYING DETAILS
class SimpleForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ["Product_SKU","image" ,"name", "available_quentity"]




class CreateForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ["Product_SKU", "category", "image", "name", "quantity", "price", "bulletpoints", "description", "available_quentity", "Product_Dimensions", "Color", "ASIN", "Material_Type", ]
        # fields = ["Product_SKU","image" ,"name","Product_id", "quantity","price","category"]

class CreateCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        
class AddCompanySkuForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['Product_SKU', "company_sku", 'company_name']  
class AddCompanyForm (forms.ModelForm):
    class Meta:
        model = CompanyName
        fields = ['companyname']
    

shop/templates/shop/product/create.html
{% extends "ordermanage/base.html" %} {% load staticfiles %} {% block title %}Create{% endblock %} {% block body %}

<section>
    <div class="section-body">
        <div class="row">

            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Create Inventry</header>
                        <div class="tools">
                            <!-- <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> -->
                            <a href=" {% url 'shop:product_list'  %}">
                                <class="btn btn-icon-toggle btn-close">
                                    <i class="md md-close"></i>
                                </a>

                        </div>
                    </div>

                    {% if messages %} {{ message }}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </div>
                    </ul>
                    {% endif %}

                    <div class="card-body">
                        <form class="col s12" action="#" method="POST" enctype="multipart/form-data">{% csrf_token %}

                            <div class="row">
                                <div class="input-field col s6">

                                    <p>
                                        <label for="id_Product_SKU">Product SKU:</label>
                                        <input type="text" name="Product_SKU" value="" required id="id_Product_SKU" maxlength="20" />
                                    </p>
                                </div>

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_image">Image:</label>
                                        <input type="file" name="image" id="id_image" />
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_name">Name:</label>
                                        <input type="text" name="name" required id="id_name" maxlength="200" />
                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_Material_Type">Material_Type:</label>
                                        <input type="text" name="Material_Type" required id="id_Material_Type" max_length="40">
                                    </p>
                                </div>

                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_quantity">Quantity:</label>
                                        <input type="number" name="quantity" required id="id_quantity" min="0" />
                                    </p>
                                </div>

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_quantity">Available Quantity:</label>
                                        <input type="number" name="available_quentity" required id="id_available_quentity" min="0" />
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_price">Price:</label>
                                        <input type="number" name="price" step="0.01" required id="id_price" />
                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_category">Category:</label>
                                        <select name="category" required id="id_category">
                                            <option value="" selected>Select</option>
                                            {% for Category_obj in Category_obj %}
                                            <option value="1">{{Category_obj.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </p>
                                </div>

                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_Product_Dimensions">Product Dimension:</label>
                                        <input type="text" name="Product_Dimensions" required id="id_Product_Dimensions" max_length="20">
                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_Color">Color:</label>
                                        <input type="text" name="Color" required id="id_Color" max_length="20">
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_bulletpoints">Bulletpoints:</label>
                                        <textarea style="height: 200px !important" ; name="bulletpoints" required id="id_bulletpoints" rows="40"></textarea>
                                    </p>
                                </div>

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_description">Descriptions:</label>
                                        <textarea style="height: 200px !important" ; name="description" required id="id_description"></textarea>
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_ASIN">ASIN:</label>
                                        <input type="text" name="ASIN" id="id_ASIN" max_length="20">
                                    </p>
                                </div>
                                <div>
                                    <div class="input-field col s3">
                                        <div class=" input-field">
                                            <button class="btn cyan waves-effect waves-light right" type="submit" value="SUBMIT">Submit
                                                <i class="material-icons right">send</i>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </form>

                        <div class="row ">
                            <div class=" input-field col s12">
                                <a href=" {% url 'shop:product_list'  %}">
                                    <button type="submit" class="btn cyan waves-effect waves-light right" style="margin-top:-125px"><i class=" close material-icons right white-text"> close </i> Close</button>
                                </a>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

shop/templates/shop/product/create1121.html
{% extends "ordermanage/base.html" %} {% load staticfiles %} {% block title %}Create{% endblock %} {% block body %}

<section>
    <div class="section-body">
        <div class="row">

            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Create Inventry</header>
                        <div class="tools">
                            <!-- <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> -->
                            <a href=" {% url 'shop:product_list'  %}">
                                <class="btn btn-icon-toggle btn-close">
                                    <i class="md md-close"></i>
                                </a>

                        </div>
                    </div>

                    {% if messages %} {{ message }}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </div>
                    </ul>
                    {% endif %}

                    <div class="card-body">
                        <form class="col s12" action="#" method="POST" enctype="multipart/form-data">{% csrf_token %}

                            <div class="row">
                                <div class="input-field col s6">

                                    <p>
                                        <label for="id_Product_SKU">Product SKU:</label>
                                        <input type="text" name="Product_SKU" value="" required id="id_Product_SKU" maxlength="20" />
                                    </p>
                                </div>

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_image">Image:</label>
                                        <input type="file" name="image" id="id_image" />
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_name">Name:</label>
                                        <input type="text" name="name" required id="id_name" maxlength="200" />
                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_Material_Type">Material_Type:</label>
                                        <input type="text" name="Material_Type" required id="id_Material_Type" max_length="40">
                                    </p>
                                </div>

                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_quantity">Quantity:</label>
                                        <input type="number" name="quantity" required id="id_quantity" min="0" />
                                    </p>
                                </div>

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_quantity">Available Quantity:</label>
                                        <input type="number" name="available_quentity" required id="id_available_quentity" min="0" />
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_price">Price:</label>
                                        <input type="number" name="price" step="0.01" required id="id_price" />
                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_category">Category:</label>
                                        <select name="category" required id="id_category">
                                            <option value="" selected>Select</option>
                                            {% for Category_obj in Category_obj %}
                                            <option value="1">{{Category_obj.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </p>
                                </div>

                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_Product_Dimensions">Product Dimension:</label>
                                        <input type="text" name="Product_Dimensions" required id="id_Product_Dimensions" max_length="20">
                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_Color">Color:</label>
                                        <input type="text" name="Color" required id="id_Color" max_length="20">
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_bulletpoints">Bulletpoints:</label>
                                        <textarea style="height: 200px !important" ; name="bulletpoints" required id="id_bulletpoints" rows="40"></textarea>
                                    </p>
                                </div>

                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_description">Descriptions:</label>
                                        <textarea style="height: 200px !important" ; name="description" required id="id_description"></textarea>
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p>
                                        <label for="id_ASIN">ASIN:</label>
                                        <input type="text" name="ASIN" id="id_ASIN" max_length="20">
                                    </p>
                                </div>
                                <div>
                                    <div class="input-field col s3">
                                        <div class=" input-field">
                                            <button class="btn cyan waves-effect waves-light right" type="submit" value="SUBMIT">Submit
                                                <i class="material-icons right">send</i>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </form>

                        <div class="row ">
                            <div class=" input-field col s12">
                                <a href=" {% url 'shop:product_list'  %}">
                                    <button type="submit" class="btn cyan waves-effect waves-light right" style="margin-top:-125px"><i class=" close material-icons right white-text"> close </i> Close</button>
                                </a>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

shop/templates/shop/product/edit.html
{% extends "ordermanage/base.html" %} {% load staticfiles %} {% block title %}Edit{% endblock %} {% block body %}

<section>
    <div class="section-body">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Edit Inventry</header>
                        <div class="tools">
                            <!-- <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> -->
                            <a href=" {% url 'shop:product_list'  %}">
                            <class="btn btn-icon-toggle btn-close">
                                <i class="md md-close"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

{% if messages %} {{ message }}
<ul class="messages">
    <div id="modal1" class="modal">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </div>
</ul>
{% endif %}

<div class="card-body">
    <form class="col s12" action="." method="POST" enctype="multipart/form-data">

        <div class="row">
            <div class="col s12">
                <div class="input-field col s6">
                    {% csrf_token %}
                    <p>
                        <label for="id_Product_SKU">Product SKU:</label>
                        <input type="text" name="Product_SKU" value="{{instance.Product_SKU}}" required id="id_Product_SKU" maxlength="20" />
                    </p>
                </div>

                <div class="input-field col s6">
                    <p>
                        <label for="id_image">Image:</label>
                        <input type="file" name="image" value="{{instance.image}}" id="id_image" />
                    </p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col s12">
                <div class="input-field col s6">
                    <p>
                        <label for="id_name">Name:</label>
                        <input type="text" name="name" value="{{instance.name}}" required id="id_name" maxlength="200" />
                    </p>
                </div>
                <div class="input-field col s6">
                    <p>
                        <label for="id_available_quentity">Availible Quantity:</label>
                        <input type="number" name="available_quentity" value="{{instance.available_quentity}}" required id="id_available_quentity" min="0" />
                    </p>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="input-field col s3">
                <div class=" input-field">
                    <button class="btn cyan waves-effect waves-light" type="submit" value="SUBMIT">Submit
                        <i class="material-icons right">send</i>

                </div>
            </div>

        </div>

    </form>
    <div class="row">
        <div class=" input-field ">
            <a href=" {% url 'shop:product_list'  %}">
                <button type="submit" class="btn cyan waves-effect waves-light right" style="margin-top:-80px"><i class=" close material-icons right white-text"> close </i> Close</button>
            </a>

        </div>
    </div>

    {% endblock %}