core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import django.core.handlers.wsgi
from . import views 
from django.conf.urls.static import static
from django.conf import settings
from .forms import LoginForm, SignUpForm, AuthenticationForm, EmailAuthenticationForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', django.contrib.auth.views.LoginView.as_view(template_name= 'mvp-2.html', authentication_form= LoginForm), name='mvp'),
    url(r'^ordermanage/', include("ordermanage.urls")),
    url(r'^signup/$', views.signup, name='signup'),      
    url(r'^logout/$',auth_views.LogoutView.as_view(), name='logout'),
    url(r'^shop/', include('shop.urls',  namespace='shop')),
    url(r'^wallmart/', include("wallmart.urls")),
    url(r'^ups/', include('ups.urls')),
    url(r'^shopify_app/', include('shopify_app.urls')),
    url(r'^ebay/', include("ebayshop.urls")),
    url(r'^amazon/', include("amazon.urls")),
    url(r'^fedex/', include("fedex.urls")),
    
    # PASSWWORD VIEWS - AUTH BASED.

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('rest_framework_social_oauth2.urls')), #heroku comment
]


"""for Lodaing Static files in django """

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""End Of  Lodaing Static files in django """

ups/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # url(r'^$', views.index, name="index")
    url(r'^$', views.UpsCreateShipment, name="ship"),
    url(r'^recovery/$', views.LabelRecoveryRequest, name="recovery"),
    url(r'^void/$', views.UpsVoidShipment, name="void"),
    url(r'^track/$', views.GetTrackingNumber, name="track"),
    url(r'^track_signature/$', views.GetTrackingNumber, name="track_signature"),
    url(r'^image_converter/$', views.image_converter, name="image_converter"),
    url(r'^address_validater/$', views.UpsAddressValidation, name="address_validater"),
    url(r'^add_upsaccount/$', views.AddUpsAccount, name="add_upsaccount"),
    url(r'^add_shipper/$', views.AddUpsShipper, name="add_shipper"),
    url(r'^add_shipfrom/$', views.AddShipFrom, name="add_shipfrom"),
    url(r'^sipper_list/$', views.ShipperListDisplay, name="sipper_list"),
    url(r'^shipfrom_list/$', views.ShipfromListDisplay, name="shipfrom_list"),
    url(r'^csv/$', views.ReadFromCsv, name="csv"),
    url(r'^exls/$', views.ReadFromExls, name="exls"),
    url(r'^shipment/$', views.CreateShipment, name="shipment")

]
 

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ValidationError


class LoginForm(AuthenticationForm):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput)
    def clean_username(self):
        username = self.data['username']
        if '@' in username:
            try:
                username = User.objects.get(email=username).username
            except ObjectDoesNotExist:
                raise ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username':self.username_field.verbose_name},
                ) 
                # print "ObjectDoesNotExist"
                return None
        return username
# class LoginForm(forms.Form):
#     username = forms.CharField(required ="True")
#     password = forms.CharField(required ="True", widget=forms.PasswordInput)

Select_Group= [
    ('indianteam', 'Indian Team'),
    ('warehouse', 'WareHouse Team'),    
    ]
    
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    # Select_Group = forms.CharField(label='Select Group', widget=forms.RadioSelect(choices=Select_Group))
    Select_Group = forms.ChoiceField(required=True, widget=forms.RadioSelect( attrs={'class': 'Radio'}), choices= Select_Group)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'Select_Group', 'password1', 'password2',)

class EmailAuthenticationForm(AuthenticationForm):
    def clean_username(self):
        username = self.data['username']
        if '@' in username:
            try:
                username = User.objects.get(email=username).username
            except ObjectDoesNotExist as e:
                raise ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username':self.username_field.verbose_name},
                )
        return username

templates/Logout.html
{% extends "base.html" %}

{% block title %}Logged out{% endblock %}

{% block content %}
<div class="" style= " float: none; margin-left: auto; margin-right: auto;">
    <h1>Logged out</h1>
    <p>You have been successfully logged out. You can click
        <a href="{% url "mvp" %}">here</a>to log-in again.
    </p>
</div>
{% endblock %}
 

templates/base.html
{% load staticfiles %}

 <!DOCTYPE html>
 <html>
 <head>
     {% include "head.html" %}
 </head>

 <body>
   {% block content %}
   {% endblock %}

   {% block JS %}

   {% endblock %}

       <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>

 </body>
 </html>

templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}

    <h1>Dashboard</h1>
    <p>Welcome to your dashboard. </p>
    <a href="{% url "logout" %}" class="btn btn-info" role="button">Logout</a>

{% endblock %}

templates/head.html
{% load staticfiles %}
<link href="{% static 'mvppage/images/logo1.png' %}" rel="shortcut icon">
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
<!--<link href="{% static 'mvppage/css/style.css/' %}" rel="stylesheet">-->
<!--<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic|Open+Sans:300italic,600italic,400,300,600,700' rel='stylesheet' type='text/css'>-->


<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description"
      content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
<meta name="keywords"
      content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
<title>{% block title %} {% endblock %}</title>

<!-- Favicons-->
<link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
<!-- Favicons-->
<link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
<!-- For iPhone -->
<meta name="msapplication-TileColor" content="#00bcd4">
<meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
<!-- For Windows Phone -->


<!-- CORE CSS-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
<style>
{% block css %}
{% endblock %}
.Radio{
      visibility: visible !important;
      opacity: 1 !important;
      display: unset !important;
      position: unset !important;     
    
    }
</style>

</head>

templates/index1.html
{% extends "base.html" %}
{% block content %}
<div id="sidebar">
  <h3>Where to start</h3>
  <h4>Check out <code style="font-size: 140%">home/views.py</code></h4>

  <p class="description">
    The index view in this demo application fetches the latest 3 orders and products and makes them available as context variables <code style="color: #218BCE">orders</code> and <code style="color: #218BCE">products</code>.
  </p>

  <h4>Check out the <code>home/index1.html</code> template</h4>

  <p class="description">
    This is the Django template you are currently looking at. It is located at:<br />
  </p>

  <p style="background: #fff; margin-left: 4px"><code>home/templates/home/index.html</code></p>

  <p class="description">
    Have a look at the markup and Django template code to see how the Shopify API is being used.
  </p>

  <h3>Additional documentation</h3>

  <p class="description">
    Become an expert:
  </p>

  <ul>
    <li>
      <a href="http://www.shopify.com/developers/api/">API documentation</a>
      <span class="note">The reference: what you can do with the Shopify API.</span>
    </li>
    <li>
      <a href="http://wiki.shopify.com/">Wiki</a>
      <span class="note">Get more information and share your knowledge.</span>
    </li>
    <li>
      <a href="http://forums.shopify.com/community">Forum</a>
      <span class="note">Ask questions and see what others already wanted to know.</span>
    </li>
  </ul>

  <h3>Once you're ready</h3>

  <p class="description">
    We'd love to see what you create using the Shopify API. 
    Find out how to share your application with the world and read the latest information on the <a href="http://www.shopify.com/developers/publishing/">API Publishing Page</a>.
  </p>
</div>


<div id="orders">
  <h2>Your recent orders</h2>
  {% if orders %}
    <ul>
    {% for order in orders %}
      <li>
        <div class="order box">
          <div class="wrapper">
            <strong><a href="https://{{ current_shop.domain }}/admin/orders/{{ order.id }}">{{ order.name }}</a></strong>
            <span class="price">{{ order.total_price }} {{ order.currency }}</span>
            <span class="highlight">{{ order.financial_status }}</span>
            by <span class="note">{{ order.billing_address.name }}</span>
          </div>
        </div>
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <em class="note">There are no orders in your store.</em>
  {% endif %}
</div>


<h2>Some of your products</h2>

{% for product in products %}
  <div class="product box">
    <div class="wrapper">
      {% if products.images %}
        <img src=="{{ product.images.first.small }}" />
      {% endif %}

      <h4><a href="https://{{ current_shop.domain }}/admin/products/{{ product.id }}">{{ product.title }}</a></h4>

      <p class="price">{{ product.price_range }} {{ current_shop.currency }}</p>
      <p style="margin-bottom: 0">{{ product.product_type }} <span class="note">type</span></p>
      <p style="margin: 0">{{ product.vendor }} <span class="note">vendor</span></p>

      <div style="clear:left"></div>
    </div>
  </div>
{% empty %}
  <em class="note">There are no products in your store.</em>
{% endfor %}

{% endblock %}

templates/js.html
 {% load static %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'mvppage/js/move-top.js' %}"></script>{# for scrolling up page #}
<script src="{% static 'mvppage/js/jquery.easing.min.js' %}"></script> {#used for srolling up nd down the paqge#} {# used to pop up login #}


<!-- for displaing error message on form -->
<!-- <script>
    $(function() {
        $("#contact-form").submit(function(e) {
            e.preventDefault();
            $form = $(this);

            $.post(document.location.url, $(this).serialize(), function(data) {
                $feedback = $("<div>").html(data).find(".form-feedback");

                $form.prepend($feedback);

            });
        });
    })
</script> -->
{% comment %} <script>
    $(document).ready(function() {
        $("#myBtn").click(function() {
            $("#myModal").modal();
        });
    });
</script> {% endcomment %}
<script>
    $(function() {
        $("#contact-form").submit(function(e) {
            e.preventDefault();
            $form =$(this);
            $.post(url, $(form).serialize())
            
        function(data){
            $feedback = $("<div>").html(data).find(".form-feedback"); 
            
            if( $('#eror').length ){
                $('#eror').remove();
                
            }
            $form.prepend($feedback);
                
            
        });
    });
            
    
    </script>
    
    

<script>
    $(document).ready(function() {
        $("#SignUpBtn").click(function() {
            $("#SignUpModal").modal();
        });
    });
</script>



{# used to slide to reespective content onclick to menubr #}
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $(".scroll").click(function(event) {
            event.preventDefault();
            $('html,body').animate({
                scrollTop: $(this.hash).offset().top
            }, 1000);
        });
    });
</script>


{# Dropdown menu in modile mode#}
<script>
    $(function() {
        var pull = $('#pull');
        menu = $('nav ul');
        menuHeight = menu.height();
        $(pull).on('click', function(e) {
            e.preventDefault();
            menu.slideToggle();
        });
        $(window).resize(function() {
            var w = $(window).width();
            if (w > 320 && menu.is(':hidden')) {
                menu.removeAttr('style');
            }
        });
    });
</script>



{# for scrolling up page #}
<script type="text/javascript">
    $(document).ready(function() {

        $().UItoTop({
            easingType: 'easeOutQuart'
        });

    });
</script>
<script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

</script>

templates/login.html
{% extends "base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}

<h1>Login</h1>


    <!-- <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}

        <p><input type="submit" value="Log-in"></p>
    </form> {% url "shopify_app.views.authenticate" %}-->
    <h1>Install</h1>

<p>Install this app in a shop to get access to its private admin data.</p>

<p style="padding-bottom: 1em"><span class="hint">Don&rsquo;t have a shop to install your app in handy? <a href="https://app.shopify.com/services/partners/api_clients/test_shops">Create a test shop.</a></span></p>

<form action="#" method="post">{% csrf_token %}
  <label for='shop'><strong>The URL of the Shop</strong>
    <span class="hint">(or just the subdomain if it&rsquo;s at myshopify.com)</span>
  </label>
  <p>
    <input id="shop" name="shop" size="45" type="text" />
    <input name="commit" type="submit" value="Install" />
  </p>
</form>


{% endblock %}

templates/navbar.html
<div id="header">
        <span class="logo">Bookmarks</span>
        {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %} class="selected"{% endif %}>
                <a href="{% url "dashboard" %}">My dashboard</a></li>
        </ul>
        {% endif %}
    </div>

templates/new.html
<table>
    <tr>
       <th>PO</th>
      <th>Company name</th>
      
      <th>Courier Method</th>
      <th>Directory Name</th>
      <th>Order Date</th>
      <th>PickUp Date</th>
      <th>Status</th>
      <th>Invoice Send</th>
      <th>Remark</th>
     
    </tr>
   {% for query in query_results_order %}
    <tr>
      <td>{{query.po}}</td>
      <td>{{query.name}}</td>
      <td>{{query.courier_method}}</td>
      <td>{{query.Directory_Name}}</td>
      <td>{{query.order_date}}</td>
      <td>{{query.pickup_date}}</td>
      <td>{{query.status}}</td>
      <td>{{query.invoice_send}}</td>
      <td>{{query.remark}}</td>
    </tr>
    {% endfor %}
    
  </table>

templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Log-in{% endblock %}
{% block css %}

body {
display: flex;
min-height: 100vh;
flex-direction: column;
}



main {
flex: 1 0 auto;
}

body {
background: #fff;
}

.input-field input[type=date]:focus + label,
.input-field input[type=text]:focus + label,
.input-field input[type=email]:focus + label,
.input-field input[type=password]:focus + label {
color: #e91e63;
}

.input-field input[type=date]:focus,
.input-field input[type=text]:focus,
.input-field input[type=email]:focus,
.input-field input[type=password]:focus {
border-bottom: 2px solid #e91e63;
box-shadow: none;
}


{% endblock %}

{% block content %}
<div class="section"></div>
<main>
    <center>
        <img src="{% static 'mvppage/images/logo.png' %}" class="img1" alt="eKnous Technology SOlutions Logo">
        <div class="section"></div>
        <h5 class="black-text">Please, login into your account</h5>
        <div class="section"></div>

        <div class="container">
            <div class="z-depth-1 grey lighten-4 row"
                 style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                 <form class="col s12" method="POST" action="">{% csrf_token %}
                    <div class='row'>
                      <div class='col s12'>
                      </div>
                    </div>
        
                    <div class='row'>
                      <div class='input-field col s6'>
                        <input type='text' name='username' autofocus required id='id_username' maxlength="150"/>
                        <label for='id_username'>User Name</label>
                      </div>
                    
                      <div class='input-field col s6'>
                        <input type='text' name='first_name' autofocus id='id_first_name' maxlength="30"/>
                        <label for='id_first_name'>First Name</label>
                      </div>
                    </div>


                      <div class='row'>
                            <div class='input-field col s6'>
                        <input type='text' name='last_name' autofocus id='id_last_name' maxlength="30"/>
                        <label for='id_last_name'>Last Name</label>
                      </div>
                    
                        <div class='input-field col s6'>
                          <input type='email' name='email' autofocus required id='id_email' maxlength="254"/>
                          <label for='id_email'>Email</label>
                        </div>
                    </div>
        
                    <div class='row'>
                        <div class='input-field col s6'>
                            <input type='password' name='password1' autofocus required id='id_password1' />
                            <label for='id_password1'>Password</label>
                          </div>
        
                      
                        <div class='input-field col s6'>
                          <input type='password' name='password2' autofocus required id='id_password2' />
                          <label for='id_password2'>Conform Password</label>
                        </div>
                    </div>
                          
                    <div class="row margin">
                        <div class="input-field col s6">
                            <input id="id_Select_Group_0" name="Select_Group" value="indianteam" type="radio" />   
                                <label for="id_Select_Group_0">Indianteam</label>
                            
                        </div>

                        <div class="input-field col s6">
                                <input id="id_Select_Group_1" name="Select_Group" value="warehouse" type="radio" />   
                                    <label for="id_Select_Group_1">Warehouse</label>
                                </div>
                            </div>
           
                        <!-- <div class='row'>
                            
        
                            <div class="input-field col s4">
                                <p>
                                    <label for="id_recycler_zip">Zip:</label>
                                    <select style="display:block" name="recycler_zip" required id="id_recycler_zip">
                                        <option value="" selected disabled hidden></option>
                                        {% for zips in zip %}
                                        <option value={{zips.zip_id}}>{{zips.zip}}</option>
                                        {% endfor %}
                                    </select>
                                </p>
                            </div>
                        </div> -->
        
                            
                    <br />
                    <center>
                      <div class='row'>
                        <button type='submit' name='btn_login' class='col s12 btn btn-large btn-custom waves-effect green' value="Login">SignUp</button>
                      </div>
                    </center>
                  </form>
</div>
</div>

</center>

</main>

{% endblock %}

templates/signup1.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Log-in{% endblock %}
{% block css %}

body {
display: flex;
min-height: 100vh;
flex-direction: column;
}



main {
flex: 1 0 auto;
}

body {
background: #fff;
}

.input-field input[type=date]:focus + label,
.input-field input[type=text]:focus + label,
.input-field input[type=email]:focus + label,
.input-field input[type=password]:focus + label {
color: #e91e63;
}

.input-field input[type=date]:focus,
.input-field input[type=text]:focus,
.input-field input[type=email]:focus,
.input-field input[type=password]:focus {
border-bottom: 2px solid #e91e63;
box-shadow: none;
}


{% endblock %}

{% block content %}
<div class="section"></div>
<main>
    <center>
        <img src="{% static 'mvppage/images/logo.png' %}" class="img1" alt="eKnous Technology SOlutions Logo">
        <div class="section"></div>
        <h5 class="black-text">Please, login into your account</h5>
        <div class="section"></div>

        <div class="container">
            <div class="z-depth-1 grey lighten-4 row"
                 style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                <form class="col s12" id="usr_login_form" method="post">
                    <div class='row'>
                        <div class='col s12'>                            
                        </div>
                    </div>
                    {% csrf_token %}
                    {{ form.as_p }}                    
      <center>
                <div class='row'>
                <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect green'>Sign up</button>        
              
          </div>
      </center>
      
  </form>
</div>
</div>

</center>

</main>

{% endblock %}