core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import django.core.handlers.wsgi
from . import views 
from django.conf.urls.static import static
from django.conf import settings
from .forms import LoginForm, SignUpForm, AuthenticationForm, EmailAuthenticationForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', django.contrib.auth.views.LoginView.as_view(template_name= 'mvp-2.html', authentication_form= LoginForm), name='mvp'),
    url(r'^ordermanage/', include("ordermanage.urls")),
    url(r'^signup/$', views.signup, name='signup'),      
    url(r'^logout/$',auth_views.LogoutView.as_view(), name='logout'),
    url(r'^shop/', include('shop.urls',  namespace='shop')),
    url(r'^wallmart/', include("wallmart.urls")),
    url(r'^ups/', include('ups.urls')),
    url(r'^shopify_app/', include('shopify_app.urls')),
    url(r'^ebay/', include("ebayshop.urls")),
    url(r'^amazon/', include("amazon.urls")),
    url(r'^fedex/', include("fedex.urls")),
    
    # PASSWWORD VIEWS - AUTH BASED.

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('rest_framework_social_oauth2.urls')), #heroku comment
]


"""for Lodaing Static files in django """

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""End Of  Lodaing Static files in django """

shop/urls.py
from django.conf.urls import url
from . import views
app_name='shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<id>\d+)/delete/$', views.product_delete, name="delete"),
    #url(r'^/create/$', views.create, name="create"),
    url(r'^product/create/$', views.create, name="create"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/company_stock/$', views.company_stock, name='company_stock'),
    url(r'^product/category/$', views.category, name='category'),
    url(r'^product/addcompany/$', views.AddCompanySku, name='addcompany'),
    url(r'^product/company/$', views.AddCompany, name='company'),
    url(r'^product/hundred/$', views.inventory_hundred_Percent, name='hundred'),
    url(r'^product/lesthantwenty/$', views.inventory_twenty, name='lesthantwenty'),
    url(r'^product/inventory_inrange/$', views.inventory_inrange, name='inventory_inrange'),
    url(r'^product/create_product/$', views.CreateProduct, name='create_product'),
    url(r'^product/shopifyGetProduct/$', views.shopifyGetProduct, name='shopifyGetProduct')
    # url(r'^company_stock/$', views.company_stock, name='company_stock'),



]

ups/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # url(r'^$', views.index, name="index")
    url(r'^$', views.UpsCreateShipment, name="ship"),
    url(r'^recovery/$', views.LabelRecoveryRequest, name="recovery"),
    url(r'^void/$', views.UpsVoidShipment, name="void"),
    url(r'^track/$', views.GetTrackingNumber, name="track"),
    url(r'^track_signature/$', views.GetTrackingNumber, name="track_signature"),
    url(r'^image_converter/$', views.image_converter, name="image_converter"),
    url(r'^address_validater/$', views.UpsAddressValidation, name="address_validater"),
    url(r'^add_upsaccount/$', views.AddUpsAccount, name="add_upsaccount"),
    url(r'^add_shipper/$', views.AddUpsShipper, name="add_shipper"),
    url(r'^add_shipfrom/$', views.AddShipFrom, name="add_shipfrom"),
    url(r'^sipper_list/$', views.ShipperListDisplay, name="sipper_list"),
    url(r'^shipfrom_list/$', views.ShipfromListDisplay, name="shipfrom_list"),
    url(r'^csv/$', views.ReadFromCsv, name="csv"),
    url(r'^exls/$', views.ReadFromExls, name="exls"),
    url(r'^shipment/$', views.CreateShipment, name="shipment")

]
 

ups/forms.py
from django import forms
from django.forms import MultiWidget
from .models import UpsLoginModel, ShipperModel, ShipFromModel

class UpsAddAcountForm(forms.ModelForm):

    class Meta:
        model = UpsLoginModel
        fields = ["username","password"]

class UpsShipperForm(forms.ModelForm):
    class Meta:
        model = ShipperModel
        fields = ['username',
                    'name',
                    'attentionname',
                    'tax_identification_number',
                    'phon_number','extension',
                    'shipper_account_number',
                    'fax_number',
                    'address_line',
                    'city',
                    'state_province_code',
                    'postal_code',
                    'country_code'
                ]
class ShipFromModelForm(forms.ModelForm):

    class Meta:
        model = ShipFromModel
        fields = '__all__'

ups/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals 

from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from .models import *
import json, requests, csv, base64, os

from ordermanage.models import *
from shop.models import *
import datetime
from .forms import UpsAddAcountForm, UpsShipperForm, ShipFromModelForm
from django.conf import settings
from . import variables

'''===========================================================
       Project Name: Ups Api
       Function Name: Add Account details
       URL: http://127.0.0.1:8000/ups/add_upsaccount
       Author: eKnous Technology Solutions
       License: https://eknous.com/license/ 
============================================================'''
def AddUpsAccount(request):
       
    if request.method == 'POST':
        form = UpsAddAcountForm(request.POST or None)              
        if form.is_valid():
            instance = form.save(commit = False)
            instance.save()
    # else:
    form = UpsAddAcountForm()

    return render (request, 'ups_account.html', {"form":form})


'''===========================================================
       Project Name: Ups Api
       Function Name: Add Shipper Details
       URL: http://127.0.0.1:8000/ups/add_ups_shipper
       Author: eKnous Technology Solutions
       License: https://eknous.com/license/ 
============================================================'''


def AddUpsShipper(request):
       
    if request.method == 'POST':
        form = UpsShipperForm(request.POST or None)              
        if form.is_valid():
            instance = form.save(commit = False)
            instance.save()
            return HttpResponseRedirect(reverse('sipper_list'))
    # else:
    form = UpsShipperForm()

    return render (request, 'ups_shipper.html', {"form":form})

'''===========================================================
       Project Name: Ups Api
       Function Name: Add Shipper Details
       URL: http://127.0.0.1:8000/ups/add_ups_shipper
       Author: eKnous Technology Solutions
       License: https://eknous.com/license/ 
============================================================'''


def AddShipFrom(request):
       
    if request.method == 'POST':
        form = ShipFromModelForm(request.POST or None)              
        if form.is_valid():
            instance = form.save(commit = False)
            instance.save()
            return HttpResponseRedirect(reverse('shipfrom_list'))
    # else:
    form = ShipFromModelForm()

    return render (request, 'ups_shipfrom.html', {"form":form})

'''===========================================================
       Project Name: Ups Api
       Function Name: Add Shipper Details
       URL: http://127.0.0.1:8000/ups/list_display
       Author: eKnous Technology Solutions
       License: https://eknous.com/license/ 
============================================================'''

def ShipperListDisplay(request):
    queryset = ShipperModel.objects.all()
    return render(request, 'ups_list.html', {'queryset':queryset, 'title': "Shipper Account"})


def ShipfromListDisplay(request):
    queryset = ShipFromModel.objects.all()
    return render(request, 'ups_list.html', {'queryset':queryset, 'title': "ShipFrom List"})




# Create your views here.
def index(request):
    return HttpResponse('finally ups done')

'''============================================
       Project Name: Ups Api
       Name: Address UPSApi
       URL: http://127.0.0.1:8000/ups
       Author: eKnous Technology Solutions
       License: https://eknous.com/license/ 
   ============================================'''

def UpsAddressValidation(request):
    url = 'https://wwwcie.ups.com/rest/AV'
    header = variables.header
    
    data ={  
            "AccessRequest":{  
                "AccessLicenseNumber":variables.AccessLicenseNumber,
                "UserId":"eknousllc",
                "Password":"eknous@2018"
            },
            "AddressValidationRequest":{  
                "Request":{  
                    "TransactionReference":{  
                        "CustomerContext":"eKnous OrdermanageUpsApi",

                    },
                    "RequestAction":"AV"
                },
                "Address":{  
                    "City":"PRINCETON",
                    "StateProvinceCode":"NJ",
                    "PostalCode":"08540"
                }
            }
        }
    response=requests.post(url, headers= header, data= json.dumps(data))
    # print response
    # return HttpResponse(dict)
    dict = json.dumps(response.json(), indent=4)    
    return render(request, "json.json" , {'dict':dict}, content_type='application/json')
'''============================================
    Project Name: Ups Api
    Name: Create ups Shipment Labal
    URL: http://127.0.0.1:8000/ups
    Author: eKnous Technology Solutions
    License: https://eknous.com/license/ 
============================================'''

def UpsCreateShipment(request): 
    shipping_Address= Address.objects.all()
    now = datetime.datetime.now().strftime("%m%d%Y%S")
    k= len(shipping_Address)
    final_file = open("UPSshippingLbl/final"+now+".html", 'wb+')
    for i in shipping_Address:
        print ("==============Address po")
        order= i.po_number
        print("order:",order.po)
        order_id = Order.objects.get(po = order.po)
        print ("==============order_id")
        print (type(order_id))
        print (order_id)
        print (order_id.status )
        print ("==============")

        shipment_service_code = order_id.courier_method.valid_code
        product_dimensions =  order_id.company_name.Product_SKU.Product_Dimensions
        dimensions = product_dimensions.split('x')
        length = dimensions[0]
        width = dimensions[1]
        height = dimensions[2]
        label_response= ""
        order_qty1 = LineTable.objects.filter(purchase_order = i.po_number)
        order_qty = 0
        for j in order_qty1:
            order_qty += int(j.order_quantity)
            print (order_qty)
            print (j.purchase_order)
        qty = 1
        print (i.po_number.status)
        for qty in range(order_qty):
            if 'OPEN' in i.po_number.status:
                print ("in loop:",len(shipping_Address))
                url = 'https://wwwcie.ups.com/rest/Ship'
                # url ='https://onlinetools.ups.com/rest/Ship'
                header =  variables.header                
                name = (i.address).split(',')                
                data = {  
                            "UPSSecurity":{  
                            "UsernameToken":variables.ups_login(request),
                            "ServiceAccessToken":{  
                                "AccessLicenseNumber": variables.AccessLicenseNumber
                            }
                            },
                            "ShipmentRequest":{  
                            "Request":{  
                                "RequestOption":"validate",
                                "TransactionReference":{  
                                    "CustomerContext":name[0]
                                }
                            },
                            "Shipment":{  
                                "Description":str(i.po_number),
                                "Shipper":variables.shipper(request),
                                "ShipTo":{  
                                    "Name":name[0],
                                    "AttentionName":name[0],
                                    "Phone":{  
                                    "Number":i.phone_number
                                    },
                                    "Address":{  
                                    "AddressLine":"100 Overlook Center",
                                    "City":"PRINCETON",
                                    "StateProvinceCode":"NJ",
                                    "PostalCode":"08540",
                                    "CountryCode":"US"
                                    }
                                },
                                "ShipFrom":variables.ShipFrom(request),
                                "PaymentInformation":{  
                                    "ShipmentCharge":{  
                                    "Type":"01",
                                    "BillShipper":{  
                                        "AccountNumber":"5238y9"
                                    }
                                    }
                                },
                                "Service":{ 
                                    "Code":shipment_service_code,
                                    "Description":"Express2"
                                },
                                "Package":{
                                    "Description":name[0],
                                    "Packaging":{  
                                    "Code":"02",
                                    "Description":str(i.po_number)
                                    },
                                    "Dimensions":{  
                                    "UnitOfMeasurement":{
                                        "Code":"IN",
                                        "Description":"Inches"
                                    },
                                    "Length":length,
                                    "Width":width,
                                    "Height":height
                                    },
                                    "PackageWeight":{  
                                    "UnitOfMeasurement":{  
                                        "Code":"LBS",
                                        "Description":"Pounds3"
                                    },
                                    "Weight":"10"

ups/templates/json.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
            <img src="data:image/gif;base64,{{ a }}" alt="Girl in a jacket">
        {% for dict in dict %}
            {{ dict|safe }}
        {% endfor %}
   </html>

ups/templates/upload_form.html
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    <h1>{{header}}</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" enctype="multipart/form-data"  method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

ups/templates/ups_account.html
{% extends "ordermanage/base.html" %} {% load staticfiles %} {% block title %}Create{% endblock %} {% block body %}
<section>
    <div class="section-body">
        <div class="row">

            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Create Inventry</header>
                        <div class="tools">
                            <!-- <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> -->
                            <a href=" {% url 'shop:product_list'  %}">
                                <class="btn btn-icon-toggle btn-close">
                                    <i class="md md-close"></i>
                                </a>

                        </div>
                    </div>

                    {% if messages %} {{ message }}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </div>
                    </ul>
                    {% endif %}

                    <div class="card-body">
                        <form class="col s12" action="#!" method="POST" enctype="multipart/form-data">{% csrf_token %}
                            <div class="input-field col s6">
                            {{ form.as_p }}
                            <input type="submit" name="submit">
                        </div>

                            <!-- <div class="row">
                                <div class="input-field col s6">

                                    <p>
                                        <label for="id_username">Username:</label>
                                        <input type="text" name="username" value="" required id="id_username" maxlength="20" />
                                    </p>
                               
                                    <p>
                                        <label for="id_password">Password:</label>
                                        <input type="text" name="password" required id="id_password" />
                                    </p>
                                </div>
                            </div>                           


                            <div class="row">
                                <div class="input-field col s6">
                                    <div class="input-field col s3">
                                        <div class=" input-field">
                                            <button class="btn cyan waves-effect waves-light right" type="submit" value="SUBMIT">Submit
                                                <i class="material-icons right">send</i>

                                        </div>

                                    </div>

                                </div>

                            </div> -->

                        </form>

                        <div class="row ">
                            <div class=" input-field col s12">
                                <a href=" {% url 'shop:product_list'  %}">
                                    <button type="submit" class="btn cyan waves-effect waves-light right" style="margin-top:-125px"><i class=" close material-icons right white-text"> close </i> Close</button>
                                </a>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

ups/templates/ups_list.html
{% extends "ordermanage/base.html" %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<section id="content">
</section>
<section class="table" style="padding-left:0px !important; ">
   <div class="row">
   <div class="col m12 s12 ">
   <div class="card  card-box">
   <div class="card-head">
      <header>{{ title }}</header>
      <div class="tools">
         <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
         <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
         <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
      </div>
   </div>
   <div class="card-body">
      <div class="table-wrap">
         <div class="table-responsive">
            {% if messages %}
            <ul class="messages">
               {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    <p class="text-danger">{{ message }}</p>
                </li>
               {% endfor %}
            </ul>
            {% endif %}
            <div class="table-responsive">
               <form action="#" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% if "Shipper Account" in title %}
                  <table id="datatable2" class="table order-column hover">
                     <thead>
                        <tr>
                           {% comment %} 
                           <th><input type="checkbox" id="checkAll"></th>
                           {% endcomment %}
                           <th><input type="checkbox" id="checkAll" ></th>
                           <th>Name</th>
                           <th>Shipper Account Number:</th>
                           <th>phone Number</th>
                           <th>Address Line</th>
                           <th>City</th>
                           <th>State Code</th>
                           <th>Zip</th>
                           <th>Country</th>
                           <!-- <th>Button</th> -->
                        </tr>
                     </thead>
                     <tbody>
                        {% for queryset in queryset %}
                        <tr>
                           <td><input type="checkbox" name="selectCheckbox"></td>
                           <td style=" font-size: 14px;">{{ queryset.name }}</td>
                           <td style="font-size: 13px; padding-left: 0px;">{{ queryset.shipper_account_number }}</td>
                           <td style=" font-size: 13px;">{{ queryset.phon_number }}</td>
                           <td style="font-size: 14px;padding-left: 40px;">{{  queryset.address_line }}</td>
                           <td style=" font-size: 14px;">{{ queryset.city }}</td>
                           <td style="font-size: 13px; padding-left: 0px;">{{ queryset.state_province_code }}</td>
                           <td style=" font-size: 13px;">{{ queryset.postal_code }}</td>
                           <td style="font-size: 14px;padding-left: 40px;">{{  queryset.country_code }}</td>
                           <!-- <td><a href="{% url 'shop:edit' id=queryset.id %}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i></a></td> -->
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
                  {% elif "ShipFrom List" in title %}
                  <table id="datatable2" class="table order-column hover">
                        <thead>
                           <tr>
                              {% comment %} 
                              <th><input type="checkbox" id="checkAll"></th>
                              {% endcomment %}
                              <th><input type="checkbox" id="checkAll" ></th>
                              <th>Name</th>
                              <th>Attention Name:</th>
                              <th>phone Number</th>
                              <th>Address Line</th>
                              <th>City</th>
                              <th>State Code</th>
                              <th>Zip</th>
                              <th>Country</th>
                              <!-- <th>Button</th> -->
                           </tr>
                        </thead>
                        <tbody>
                           {% for queryset in queryset %}
                           <tr>
                              <td><input type="checkbox" name="selectCheckbox"></td>
                              <td style=" font-size: 14px;">{{ queryset.name }}</td>
                              <td style="font-size: 13px; padding-left: 0px;">{{ queryset.attentionname }}</td>
                              <td style=" font-size: 13px;">{{ queryset.phon_number }}</td>
                              <td style="font-size: 14px;padding-left: 40px;">{{  queryset.address_line }}</td>
                              <td style=" font-size: 14px;">{{ queryset.city }}</td>
                              <td style="font-size: 13px; padding-left: 0px;">{{ queryset.state_province_code }}</td>
                              <td style=" font-size: 13px;">{{ queryset.postal_code }}</td>
                              <td style="font-size: 14px;padding-left: 40px;">{{  queryset.country_code }}</td>
                              <!-- <td><a href="{% url 'shop:edit' id=queryset.id %}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i></a></td> -->
                           </tr>
                           {% endfor %}
                        </tbody>
                     </table>
                  
                  {% endif %}
               </form>
            </div>
         </div>
      </div>
   </div>
</section>
{% endblock %}

ups/templates/ups_shipfrom.html
{% extends "ordermanage/base.html" %} {% load staticfiles %} {% block title %}Create{% endblock %} {% block body %}
<section>
    <div class="section-body">
        <div class="row">

            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Shipper Form</header>
                        <div class="tools">
                            <!-- <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> -->
                            <a href=" {% url 'shop:product_list'  %}">
                                <class="btn btn-icon-toggle btn-close">
                                    <i class="md md-close"></i>
                                </a>

                        </div>
                    </div>

                    {% if messages %} {{ message }}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </div>
                    </ul>
                    {% endif %}

                    <div class="card-body">
                        <form class="col s12" action="#!" method="POST" enctype="multipart/form-data">{% csrf_token %}
                            <div class="input-field col s6">
                                <p></p>
                            {{ form.as_p }}
                            <input type="submit" name="submit">
                        </div>

                            

                        </form>

                        <div class="row ">
                            <div class=" input-field col s12">
                                <a href=" {% url 'shop:product_list'  %}">
                                    <button type="submit" class="btn cyan waves-effect waves-light right" style="margin-top:-125px"><i class=" close material-icons right white-text"> close </i> Close</button>
                                </a>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

ups/templates/ups_shipper.html
{% extends "ordermanage/base.html" %} {% load staticfiles %} {% block title %}Create{% endblock %} {% block body %}
<section>
    <div class="section-body">
        <div class="row">

            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Shipper Form</header>
                        <div class="tools">
                            <!-- <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> -->
                            <a href=" {% url 'shop:product_list'  %}">
                                <class="btn btn-icon-toggle btn-close">
                                    <i class="md md-close"></i>
                                </a>

                        </div>
                    </div>

                    {% if messages %} {{ message }}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </div>
                    </ul>
                    {% endif %}

                    <div class="card-body">
                        <form class="col s12" action="#!" method="POST" enctype="multipart/form-data">{% csrf_token %}
                            <div class="input-field col s6">
                                <p></p>
                            {{ form.as_p }}
                            <input type="submit" name="submit">
                        </div>

                            

                        </form>

                        <div class="row ">
                            <div class=" input-field col s12">
                                <a href=" {% url 'shop:product_list'  %}">
                                    <button type="submit" class="btn cyan waves-effect waves-light right" style="margin-top:-125px"><i class=" close material-icons right white-text"> close </i> Close</button>
                                </a>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}