core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import django.core.handlers.wsgi
from . import views 
from django.conf.urls.static import static
from django.conf import settings
from .forms import LoginForm, SignUpForm, AuthenticationForm, EmailAuthenticationForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', django.contrib.auth.views.LoginView.as_view(template_name= 'mvp-2.html', authentication_form= LoginForm), name='mvp'),
    url(r'^ordermanage/', include("ordermanage.urls")),
    url(r'^signup/$', views.signup, name='signup'),      
    url(r'^logout/$',auth_views.LogoutView.as_view(), name='logout'),
    url(r'^shop/', include('shop.urls',  namespace='shop')),
    url(r'^wallmart/', include("wallmart.urls")),
    url(r'^ups/', include('ups.urls')),
    url(r'^shopify_app/', include('shopify_app.urls')),
    url(r'^ebay/', include("ebayshop.urls")),
    url(r'^amazon/', include("amazon.urls")),
    url(r'^fedex/', include("fedex.urls")),
    
    # PASSWWORD VIEWS - AUTH BASED.

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^auth/', include('rest_framework_social_oauth2.urls')), #heroku comment
]


"""for Lodaing Static files in django """

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""End Of  Lodaing Static files in django """

ordermanage/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from views import OrderListAPIView

urlpatterns = [
    url(r'^$', OrderListAPIView.as_view(), name='index' )
]

ordermanage/urls.py
from django.conf.urls import url
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"), #main dashbord   
    url(r'^(?P<pk>[^/]+)/active/$', views.active_edit, name="active"), # warehouse    
    url(r'^create/$', views.create, name="create"), # indian team &superuser
    url(r'^404/$', views.errorpage, name="404"), #
    url(r'^(?P<pk>[^/]+)/details', views.details, name="details"), # detail page for indian And admin    
    url(r'^(?P<pk>[^/]+)/edit/$', views.edit, name="edit"),# for main edit
    url(r'^(?P<pk>[^/]+)/update/$', views.single_edit, name="update"), 
    
    url(r'^update-status/$', views.update_status, name="update-status"), #test
    url(r'^open/$', views.OpenOrder, name="open"),
    
    url(r'^openorder/$', views.OperationOpenorder, name="openorder"),
    url(r'^whopenorder/$', views.WhOpenorder, name="whopenorder"),
    url(r'^twodaysopen/$', views.TwodaysOpen, name="twodaysopen"),
    url(r'^threedaysopen/$', views.ThreedaysOpen, name="threedaysopen"),
    url(r'^courier-method/$', views.couriermethod, name="courier-method"),
    
    url(r'^fullfill/$', views.OrderFullfill, name='fullfill'),
    url(r'^inventory/$', views.CreateInventory, name='inventory'),
    # url(r'^create_product/$', views.CreateProduct, name='create_product'),
    # url(r'^token1/$', views.ShopifyLogin, name='token1'),
    # url(r'^catch/$', views.ShopifyRedirect, name='catch'),
    url(r'^createproduct/$', views.products, name='createproduct'),
    url(r'^createinventory/$', views.CreatePublicInventory, name='createinventory'),
    url(r'^Orderfullfill/$', views.OrderPublicFullfill, name='Orderfullfill') 

    # url(r'^(?P<id>[^/]+)/update/$', views.single_edit, name="update"), 

]
 

shop/urls.py
from django.conf.urls import url
from . import views
app_name='shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<id>\d+)/delete/$', views.product_delete, name="delete"),
    #url(r'^/create/$', views.create, name="create"),
    url(r'^product/create/$', views.create, name="create"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/company_stock/$', views.company_stock, name='company_stock'),
    url(r'^product/category/$', views.category, name='category'),
    url(r'^product/addcompany/$', views.AddCompanySku, name='addcompany'),
    url(r'^product/company/$', views.AddCompany, name='company'),
    url(r'^product/hundred/$', views.inventory_hundred_Percent, name='hundred'),
    url(r'^product/lesthantwenty/$', views.inventory_twenty, name='lesthantwenty'),
    url(r'^product/inventory_inrange/$', views.inventory_inrange, name='inventory_inrange'),
    url(r'^product/create_product/$', views.CreateProduct, name='create_product'),
    url(r'^product/shopifyGetProduct/$', views.shopifyGetProduct, name='shopifyGetProduct')
    # url(r'^company_stock/$', views.company_stock, name='company_stock'),



]

ups/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # url(r'^$', views.index, name="index")
    url(r'^$', views.UpsCreateShipment, name="ship"),
    url(r'^recovery/$', views.LabelRecoveryRequest, name="recovery"),
    url(r'^void/$', views.UpsVoidShipment, name="void"),
    url(r'^track/$', views.GetTrackingNumber, name="track"),
    url(r'^track_signature/$', views.GetTrackingNumber, name="track_signature"),
    url(r'^image_converter/$', views.image_converter, name="image_converter"),
    url(r'^address_validater/$', views.UpsAddressValidation, name="address_validater"),
    url(r'^add_upsaccount/$', views.AddUpsAccount, name="add_upsaccount"),
    url(r'^add_shipper/$', views.AddUpsShipper, name="add_shipper"),
    url(r'^add_shipfrom/$', views.AddShipFrom, name="add_shipfrom"),
    url(r'^sipper_list/$', views.ShipperListDisplay, name="sipper_list"),
    url(r'^shipfrom_list/$', views.ShipfromListDisplay, name="shipfrom_list"),
    url(r'^csv/$', views.ReadFromCsv, name="csv"),
    url(r'^exls/$', views.ReadFromExls, name="exls"),
    url(r'^shipment/$', views.CreateShipment, name="shipment")

]
 

ordermanage/models.py
from __future__ import unicode_literals
import django.core.handlers.wsgi  # Anuj not sure if this is used.
import datetime
from django.utils import timezone
from django.conf import settings  # Anuj not sure if this is used.
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from shop.models import *
# from wallmart.models import *
from django.forms import ModelChoiceField
from django.core import validators
from django.core.validators import RegexValidator
# import json, urllib3, shopify, requests


# These are generat status t0 be used across applications
# -----------------------------------------------

class GeneralStatus(models.Model):
    GENERAL_STATUS_CHOICES = (
        ('YES', 'YES'),
        ('NO', 'NO'),
        ('NA', 'NA'),
    )


class StatusChoice(models.Model):
    STATUS_CHOICES = (
        ('OPEN', 'OPEN'),
        ('CLOSE', 'CLOSE'),
        ('NA', 'NA'),
    )  # Status of the order


class PortalType(models.Model):
    PORTAL_CHOICES = (
        ('RETAIL', 'RETAIL'),
        ('ONINE', 'ONLINE'),
    )  # Status of the order


# -----------------------------------------------
# Done
# -----------------------------------------------
# Create your models here.
# seperate table for company Name
# shivam-  This is not company table which we are using 
class Company1(models.Model):
    company_id = models.AutoField(primary_key=True, verbose_name="Company ID")  
    company_name = models.CharField(max_length=500, 
                                    blank=True, 
                                    null=True, 
                                    verbose_name='Company Name',
                                    unique=True)
    Product_SKU = models.ForeignKey(Product, 
                                    related_name='prduct_sku',on_delete=models.CASCADE)
    company_sku = models.CharField(max_length=255)

    def __unicode__(self):
        return (self.company_sku)

class CourierMethod(models.Model):
    courier_method = models.CharField(max_length=256, unique=True)
    valid_code = models.CharField(max_length=6, verbose_name="Service Code", unique=None)
    def __unicode__(self):
        return (self.courier_method)

class Order(models.Model): 
    # Removed for Ebay order id
    # alphanumeric            = RegexValidator(r'^[0-9a-zA-Z]*$',
    #                                             'Only alphanumeric characters are allowed.'), validators=[alphanumeric]
    
    user                    = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')    
    po                      = models.CharField(max_length=50, primary_key=True)
    name                    = models.CharField(max_length=540)    
    # company_name            = models.ForeignKey(CompanyName, related_name='Company_company_name')
    company_name            = models.ForeignKey(Company, related_name='Company_company_name',on_delete=models.CASCADE) # change for company display
    courier_method          = models.ForeignKey(CourierMethod, related_name='CourierMethod_courier_method',on_delete=models.CASCADE) 
    Directory_Name          = models.CharField(max_length=256)  
    order_date              = models.DateField(auto_now_add=True, blank=False, null=False) 
    order_po_date           = models.DateField(default=datetime.date.today)  
    pickup_date             = models.DateField(blank=True, null=True)  
    carrier_date            = models.IntegerField(default=128, blank=True,
                                       null=True)  
    asn_sent                = models.CharField(max_length=128,
                                                choices=GeneralStatus.GENERAL_STATUS_CHOICES,
                                                default="NO", 
                                                blank=False, 
                                                null=False,
                                                verbose_name='ASN Sent?')  
    status                  = models.CharField(max_length=128, 
                                                choices=StatusChoice.STATUS_CHOICES,
                                                default="OPEN")
    warehouse_staff_status  = models.CharField(max_length=10, 
                                                verbose_name='Wharehouse Status',
                                                choices=StatusChoice.STATUS_CHOICES, 
                                                default="OPEN", 
                                                blank=False,
                                                null=False)
    invoice_send            = models.CharField(verbose_name='Invoice Raised', 
                                                choices=GeneralStatus.GENERAL_STATUS_CHOICES,
                                                default="NO", 
                                                max_length=4)
    remark                  = models.TextField(max_length=524, 
                                                blank=True, 
                                                null=True)
    Warehouse_remark        = models.TextField(max_length=524, 
                                                blank=True, 
                                                null=True)
    flag                    = models.IntegerField(blank=True, null=True)
    traking_number          = models.CharField(max_length=524, blank= True, null= True)

    def __unicode__(self):
        return (self.po)    
    def get_absolute_url(self):
        return reverse('order:index', args = [self.po])


################
# Remark table # 
################

class remark(models.Model):
    remark_po   = models.ForeignKey(Order, related_name = "remark1",verbose_name = 'Remark PO',on_delete=models.CASCADE)
    user        = models.ForeignKey(User, on_delete = models.CASCADE, related_name='User_username') # Anuj Please be consistent and use Related names everyehwere you are specifying a Foriegn Keys - TODO
    comment     = models.CharField(max_length = 500,verbose_name = 'Remark')    
    date        = models.DateTimeField(auto_now_add = True, auto_now=False) # Anuj - changed


'''   line table '''


class LineTable(models.Model):
    purchase_order  = models.ForeignKey(Order, related_name='Order_purchase_order',on_delete=models.CASCADE)   
    vendor_SKU      = models.CharField(max_length=256, blank=False,null=False)
    order_quantity  = models.IntegerField(default = 1,null = False, blank = False)

    def __unicode__(self):
        return str(self.order_quantity)

    # FOR getting absolute url
    def get_absolute_url(self):
        return reversed("ordermanage:edit", kwargs={"pk": self.purchase_order})


# for po sku
class Sku_Table(models.Model):    
    Po_request = models.ForeignKey(Order, related_name='Order_po_order',on_delete=models.CASCADE)
    Product_Sku = models.CharField(max_length=256, default='', null=False,blank=False)
    company_name = models.ForeignKey(Company1, related_name='Company1_ompany_name',on_delete=models.CASCADE)
    order_quantity = models.IntegerField(default='0')

    def __unicode__(self):
        return (self.Product_Sku)
#     # nothing this is used if we need to use some other dbtable  place of existing 
#     # class Meta: # Anuj - WHat is this field and why ?
#     #     db_table = "ordermanage"


class GetOrder(models.Model):
    customer_id = models.CharField(max_length =200)
    customer_name = models.CharField(max_length =200)
    contact_number = models.BigIntegerField( default=True, null=True, blank=True)

    def __str__(self):
        return self.customer_name

class ShopifyAccessToken(models.Model):
    shopify_shop = models.CharField(primary_key = True, max_length =200, null=False, blank=False)
    access_token = models.CharField( max_length =200, null=False, blank=False)
    scope = models.CharField(max_length =200, null=False, blank=False)

    def __unicode__(self):
        return self.access_token

class Address(models.Model):
    po_number = models.ForeignKey(Order,on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=256, null=True)    
    address = models.CharField(max_length=256, null=True)
    city = models.CharField(max_length=256, null=True)
    state = models.CharField(max_length=256, null=True)
    zip = models.CharField(max_length=15, null=True)
    phone_number = models.CharField(max_length=20, null=True)

    def __str__(self):
        return str(self.po_number)

ordermanage/api/views.py
from rest_framework.generics import ListAPIView
from ordermanage.models import Order

class OrderListAPIView(ListAPIView):
    queryset= Order.objects.all()

ordermanage/templates/ordermanage/couriermethod.html
{% extends "ordermanage/base.html" %}
{% load staticfiles %}
 {% block title %}Create{% endblock %}

{% block body %}

<section>
       <div class="section-body">
               <div class="row">
                       <div class="col s12">
                               <div class="card">
                                       <div class="card-head">
                                               <header>Add Company</header>
                                               <div class="tools">
                                                       <!-- <a class="btn btn-icon-toggle btn-collapse">
                                                               <i class="fa fa-angle-down"></i>
                                                       </a> -->
                                                       <a href=" {% url 'shop:product_list'  %}">
                                                       <class="btn btn-icon-toggle btn-close">
                                                               <i class="md md-close"></i>
                                                       </a>
                                               </div>
                                       </div>

                                       

                                       {% if messages %}
                                       {{ message }}
                                       <ul class="messages">
                                           <div id="modal1" class="modal">
                                               <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                                               <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                                   {% endfor %}
                                           </div>
                                       </ul>
                                       {% endif %}




                                       
               <div class="card-body">
                    <div class="table-responsive">
                         <form  class="col s6" action="" method="POST" enctype="multipart/form-data"><table id="datatable2" class="table order-column hover">{% csrf_token %}
                                <div class="input-field col s6">
                                <table class="table table-striped table-condensed">
                                        <thead class="thead">
                                            <tr>

                                               
                                                <th><input type="checkbox" id="checkAll" ></th>
                                                <th>Company Id</th>
                                                <th>Courier Method</th> 
                                     
                                        </tr>
                                        </thead>
                                        <tbody>
                                          {% for couriermethod in all_couriermethod %}
                              
                                          <tr style=" line-height: 35px;">
                                              <td><input type="checkbox" name="selectCheckbox" id="{{couriermethod.courier_method}}"></td>
                                              <td>{{couriermethod.id}}</a></td>
                                              <td>{{couriermethod.courier_method}}<br></td>
                                              
                              
                              
                              
                                          </tr>
                                       
                                        {% endfor %}
                                      
                                      </tbody>
                                    </table>
                                    <div style="clear: both;"></div>
                                </div>
                              
                   
                <div class="input-field col s4">
                                <label for="id_courier_method">Courier Method Name:</label>{{ form.courier_method }}
                      </div>
                                    
                     <div class="input-field col s2">
                        <div class=" input-field">
                                <button class="btn cyan waves-effect waves-light right" type="submit" value="SUBMIT">Submit
                                    <i class="material-icons right">send</i>
                      </div>
                </div>
               

                      
                       
                    </form>
                    
                    <div class="row">
                                <div class="col s12"> 
                            <div class="input-field">
                        
                                <a href= " {% url 'shop:product_list'  %}"><button type="submit" class="btn cyan waves-effect waves-light right"><i class=" close material-icons right white-text">close</i>Close</button>
                                </a>
                        
                            </div>
                        </div>
                        </div>

                </div>
             </div>
                </div>
               </div>
       </div>
       </div>
</section>


<!-- <div class="row">
        <div class="col s12"> 
    <div class="form-group1 sec">

        <a href= " {% url 'shop:product_list'  %}"><button type="submit" class="btn cyan waves-effect waves-light"><i class=" close material-icons right white-text">close</i>Close</button>
        </a>

    </div>
</div>
</div> -->
{% endblock %}

ordermanage/templates/ordermanage/css.html
{% load staticfiles %}

<!-- BEGIN META -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="keywords" content="">
<meta name="description" content="">
<!-- END META -->

<!-- BEGIN STYLESHEETS -->



<!-- <link type="text/css" rel="stylesheet" href="{% static 'ordermanage/css/bootstrap.css' %}" /> -->
<link type="text/css" rel="stylesheet" href="{% static 'ordermanage/css/materialadmin.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'ordermanage/css/material-design-iconic-font.min.css' %}" />{#used to display iconic#}

<link href="{% static 'ordermanage/img/logo1.png' %}" rel="shortcut icon">

ordermanage/templates/ordermanage/edit.html
{% extends "ordermanage/base.html" %} {% load crispy_forms_tags %} {% load staticfiles %} {% block title %}Edit{% endblock %} {% if user.is_authenticated %} {% if user.is_active %} {% block body %}


<section>
    <div class="section-body">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-head">
                        <header>Edit PO</header>
                        <div class="tools">
                            {% comment %} <a class="btn btn-icon-toggle btn-collapse">
                                <i class="fa fa-angle-down"></i>
                            </a> {% endcomment %}
                            <a href="{% url 'index' %}" class="btn btn-icon-toggle btn-close">
                                <i class="md md-close"></i>
                            </a>
                        </div>
                    </div>


                    {% if messages %}
                    <ul class="messages">
                        <div id="modal1" class="modal">
                            <a href="#" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class="material-icons">close</i></a> {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </div>
                    </ul>
                    {% endif %} {{ block_quantity }}
                    <!-- Form start From hear-->
                    <div class="card-body">
                        <form class="col s12" action="#" method="POST">{% csrf_token %}

                            <div class="row">

                                <div class="input-field col s6">


                                    <p><label>{{ form.po.label }}:</label> {{form.po}}
                                </div>

                                <!-- <div class="input-field col s6">
                                    <p><label>{{ form.order_date.label }}:</label> {{form.order_date}}</p>
                                </div> -->
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p><label>{{ form.pickup_date.label }}:</label> {{form.pickup_date}}</p>
                                </div>

                                <div class="input-field col s6">
                                    <p><label>{{ form.asn_sent.label }}:</label> {{form.asn_sent}}</p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">


                                    <p><label>{{ form.invoice_send.label }}:</label> {{form.invoice_send}}</p>
                                </div>

                                <div class="input-field col s6">
                                    <p><label>{{ form.status.label }}:</label> {{form.status}}</p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <p><label>{{ form.traking_number.label }}:</label> {{form.traking_number}}</p>
                                </div>

                                <div class="input-field col s6">
                                    <p><label>{{ form.Warehouse_remark.label }}:</label> {{form.Warehouse_remark}}
                                </div>
                            </div> 



                            <div class="row">
                                <div class="clo s12">

                                    <div class="col 6 input-field">
                                        <div class=" input-field">
                                            <button class="btn cyan waves-effect waves-light right" type="submit" value="SUBMIT">Submit
                                                <i class="material-icons right">send</i>

                                        </div>
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}
{% endif %}
<h1>You are not authorized to view this page.</h1>

{% endif %}

ordermanage/templates/ordermanage/sidebar1.html
<!--==========================================================================
    Project Name: OrderManage
    Theme Name: Sidebar 
    URL: https://eknous.com
    Author: eKnous Technology Solutions
    License: https://eknous.com/license/
===========================================================================-->



{% load staticfiles %}

<!-- BEGIN MENUBAR-->
<div id="menubar" class="menubar-inverse ">
    <div class="menubar-fixed-panel">


    </div>
    <div class="menubar-scroll-panel">


        <!-- BEGIN MAIN MENU -->
        <ul id="main-menu" class="gui-controls">

            <li class="menu-1">

                <div class="gui-icon"><i class="md-perm-identity"></i></div>
                <h6 class="user"><span class="title">{{ user }}</span ></h6>
            </li>

            <!-- BEGIN DASHBOARD -->
            <li class="menu-1">
                {% comment %} <a href="{% url 'index' %}" class="active"> {% endcomment %}
                <a href="{%url 'index'%}">
                <div class="gui-icon"><i class="md md-home" ></i></div>
                <h6><span class="title">Dashboard</span></h6>
                </a>
            </li>
            <!--end /menu-li -->
            <!-- END DASHBOARD -->


            
        

            <!--fOR WARE HOUSE dASHBOARD -->
            {% if request.user.is_superuser or "indianteam" in group1.name  %}
            <!-- BEGIN ORDER -->
                <li>
                    <a class="gui-folder " data-toggle="dropdown">
                        <div class="gui-icon"><i class="material-icons" style="padding: 7px; color: #fff;">add_shopping_cart</i></div>
                        <h6><span class="title">Order Manage</span></h6>
                    </a>

                    <!--start submenu -->
                    <ul>
                        <li class="gui-folder ">
                            <!-- <a href="{% url 'index' %}"><span>Order Manage Dasboard</span></a> -->
                        </li>
                        <li class="gui-folder ">
                            <a href="{% url 'create' %}"><span>Create Order</span>
                            </a>
                        </li>

                    </ul>
                    <!--end /menu-li -->
                </li>
            {% endif %}
           
                <li>
                    <a class="gui-folder " data-toggle="dropdown">
                        <div class="gui-icon"><i class="material-icons" style="padding: 7px; color: #fff;">add_shopping_cart</i></div>
                        <h6><span class="title">Inventry Dashboard </span></h6>
                    </a>
                    <ul>
                        <li class="gui-folder ">
                            <a href="{% url 'shop:product_list' %}">
                                <span>Inventry Dashboard </span></a>
                        </li>
                        
                        <li class="gui-folder ">
                            <a href="{% url 'shop:company_stock' %}">
                                <span>Inventry Quantity </span>
                            </a>
                        </li> 
                        <li class="gui-folder ">
                            <a href="{% url 'shop:company' %}">
                                <span>Company</span>
                            </a>
                        </li>
                        <li class="gui-folder ">
                            <a href="{% url 'courier-method' %}">
                                <span>Courier Method</span>
                            </a>
                        </li>
                        {% if request.user.is_superuser or "warehouse" in group1.name  %}
                        <li class="gui-folder ">
                            <a href="{% url 'shop:create' %}">
                                <span>Create Inventry</span>
                            </a>
                        </li>
                        <li class="gui-folder ">
                            <a href="{% url 'shop:addcompany' %}">
                                <span>Add Company Sku</span>
                            </a>
                        </li>
                        <li class="gui-folder ">
                            <a href="{% url 'shop:category' %}">
                                <span>Create Category</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
                
               

                
                <li class="menu-1">
                    <a href="{% url 'logout' %}?next={% url 'mvp' %}">
                        <div class="gui-icon"><i class="material-icons" style="padding: 7px; color: #fff;">power_settings_new </i></div>
                        <h6><span class="title">Logout</span ></h6>
                    </a>
                </li>
        </ul><!--end .main-menu -->
          <!-- END MAIN MENU -->
      
      
        </div><!--end .menubar-scroll-panel-->
      </div><!--end #menubar-->
      <!-- END MENUBAR -->